version: '3'
services:
  db:
    image: mysql:8.0
    container_name: gotech-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: gotechimobiliariaideal
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  app:
    build: .
    container_name: gotech-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gotechimobiliariaideal?user=root&password=12345
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: java -jar /app/app.jar
volumes:
  db_data:
